name: stack-magento-cs
canonical: 1-pmzso-ik_ihdz9slrfpl
author: Ja
description: Ty
type: stack
image: ""
keywords: []
technologies: []
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      destination: ($ project $)/pipeline/variables-($ environment $).yml
      path: pipeline/variables.sample.yaml
