name: stack-magento-cs
canonical: 3-q7q3x4558ojjjf2wg4k0
author: Ja
description: Ty
type: stack
image: ""
keywords: []
technologies: []
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      destination: ($ project $)/pipeline/variables-($ environment $).yml
      path: pipeline/variables.sample.yaml
